### ISSUE TITLE
Fix typos for the Data Structure course content

### ISSUE THREAD

**Issue by A-Alaa** [sbme-tutorials/sbme-tutorials.github.io#1]
E.g C++ syntax, grammatical or spelling. Either in notes or slides.
**Only editions inside [sbme-tutorials.github.io/2018/data-structures](https://github.com/sbme-tutorials/sbme-tutorials.github.io/tree/master/2018/data-structures) are accepted.**

**Comment by biomedicalengineerahmad** [comment]
Shouldn`t this command be CTRL + ALT + T ??
![image](https://user-images.githubusercontent.com/43472368/56604784-154fd800-6603-11e9-9401-dca8aa9e1e56.png)

**Comment by biomedicalengineerahmad** [comment]
![image](https://user-images.githubusercontent.com/43472368/56616804-8cdf3080-661e-11e9-8809-deb7efe6572d.png)
shouldn`t terminal command be CTRL+ALT+T ?

**Comment by A-Alaa** [comment]
Yes

> ![image](https://user-images.githubusercontent.com/43472368/56616804-8cdf3080-661e-11e9-8809-deb7efe6572d.png)
> shouldn`t terminal command be CTRL+ALT+T ?

Yes

**Comment by Almotasem100** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/43905087/56810556-db671780-6836-11e9-9bda-1eab5cf806c9.png)

Shouldn't be there a { ++i;} in the end of the while loop ?
