### ISSUE TITLE
A very minor issue about CMake

### ISSUE THREAD

**Issue by BassamMasry** [sbme-tutorials/sbme-tutorials.github.io#10]
The CMake wiki has moved from its website to gitlab, so the link provided in [CMake tutorial](https://sbme-tutorials.github.io/2019/data-structures/notes/cmake.html)

![Screenshot_2019-04-19 CMake Useful Variables - KitwarePublic](https://user-images.githubusercontent.com/43927300/56415042-c3b6ee80-628c-11e9-980b-2caab7761d53.png)
____________________
It should point to [Useful variables](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Useful-Variables)

I know this is a very trivial issue but some people may get discouraged from reading if they thought they should search for the topic

**Comment by A-Alaa** [comment]
I agree, create a PR for it.
Sent from my iPhone

On Apr 19, 2019, at 10:22 AM, BassamMasry <notifications@github.com<mailto:notifications@github.com>> wrote:


The CMake wiki has moved from its website to gitlab, so the link provided in CMake tutorial

[Screenshot_2019-04-19 CMake Useful Variables - KitwarePublic]<https://user-images.githubusercontent.com/43927300/56415042-c3b6ee80-628c-11e9-980b-2caab7761d53.png>

________________________________

It should point to Useful variables

I know this is a very trivial issue but some people may get discouraged from reading if they thought they should search for the topic

**Comment by BassamMasry** [comment]
Done

**Comment by A-Alaa** [comment]
Fixed by #12 
Thanks
