### ISSUE TITLE
week 1 : The counter in the while loop isn't incremented 

### ISSUE THREAD

**Issue by Almotasem100** [sbme-tutorials/sbme-tutorials.github.io#19]
![Screenshot (20)](https://user-images.githubusercontent.com/43905087/56826064-796cd900-685b-11e9-9064-70c251571aa0.png)

**Comment by Almotasem100** [comment]
Note : Something is missed up with the whole slides of week 6
             as it doesn't the total algorithm performance.
![Screenshot (26)](https://user-images.githubusercontent.com/43905087/56826249-0748c400-685c-11e9-8e83-f2bc4ed29dd4.png)

**Comment by A-Alaa** [comment]
> Note : Something is missed up with the whole slides of week 6
> as it doesn't show the total algorithm performance.
> ![Screenshot (26)](https://user-images.githubusercontent.com/43905087/56826249-0748c400-685c-11e9-8e83-f2bc4ed29dd4.png)

You just need to refresh the page

**Comment by Almotasem100** [comment]
What about the while loop ?
![image](https://user-images.githubusercontent.com/43905087/56851224-ceb4f300-690c-11e9-8ec8-d056a76fb6ff.png)
