### ISSUE TITLE
All these structs are missing a semicolon after the closing bracket

### ISSUE THREAD

**Issue by Almotasem100** [sbme-tutorials/sbme-tutorials.github.io#20]
![Screenshot (21)](https://user-images.githubusercontent.com/43905087/56831149-ac699980-6868-11e9-85ef-8c31b69fe234.png)
![Screenshot (22)](https://user-images.githubusercontent.com/43905087/56831154-ad9ac680-6868-11e9-80ab-8604e61aea45.png)
![Screenshot (23)](https://user-images.githubusercontent.com/43905087/56831158-af648a00-6868-11e9-936b-27499d7f5040.png)
![Screenshot (29)](https://user-images.githubusercontent.com/43905087/56831398-3b76b180-6869-11e9-989a-d1853f4296d0.png)

**Comment by A-Alaa** [comment]
Fixed
