### ISSUE TITLE
Week 1- Part 1 

### ISSUE THREAD

**Issue by SalmaZakariia** [sbme-tutorials/sbme-tutorials.github.io#21]
In If-else if, type of mark should be int not char.

**Comment by A-Alaa** [comment]
I believe it is already `int`.

**Comment by SalmaZakariia** [comment]
but in the slides it is written char mark = 73;
________________________________

**Comment by A-Alaa** [comment]
> char mark

I see, yes it had to be `int mark = 73;`. Thank you.

By the way, that was legal in C++. You can assign integers to `char` type. But make sure that your integer is less that `255`.
