### ISSUE TITLE
Grades sheet redirects to wrong file

### ISSUE THREAD

**Issue by BassamMasry** [sbme-tutorials/sbme-tutorials.github.io#28]
Good evening.
The grades sheet at 2020/CG_HEMN/CG.md file does not redirect to a correct excel sheet (this is not our class)
@EslamAdel

**Comment by EslamAdel** [comment]
Yes ,it is the credit hours class. 
The link of your class is found here 
https://sbme-tutorials.github.io/2020/CG/CG.html
