### ISSUE TITLE
Week 8: slides 10,11,12 (extract) same image

### ISSUE THREAD

**Issue by BassamMasry** [sbme-tutorials/sbme-tutorials.github.io#7]
On slides 10,11,12 they show the same image of extracting (deleting) from a heap.
They does not show the steps

**Comment by BassamMasry** [comment]
The same issue with notes

**Comment by BassamMasry** [comment]
A pull request was made with the error fixed

**Comment by A-Alaa** [comment]
Fixed

**Comment by BassamMasry** [comment]
@A-Alaa 
I think there was a problem when you built the new file
......
A screenshot from slides
![Screenshot_2019-04-19 Week 8 Heaps, Priority Queues (ADT), and Shortest Path Problem](https://user-images.githubusercontent.com/43927300/56414243-3ecad580-628a-11e9-800a-8ad02126cec0.png)
____________
A screenshot from my forked repo
![Screenshot_2019-04-19 BassamMasry sbme-tutorials github io](https://user-images.githubusercontent.com/43927300/56414258-4b4f2e00-628a-11e9-81c1-5677e8f6a004.png)

**Comment by BassamMasry** [comment]
@A-Alaa 
I knew what the problem is.. you changed the numbers of the file name.
Actually the three photos have entirely different file names
