### ISSUE TITLE
Typo on week 8 slide 13: Min-heap -> Max-heap

### ISSUE THREAD

**Issue by BassamMasry** [sbme-tutorials/sbme-tutorials.github.io#8]
The title of slide 13 should be "Implementation of *Max-Heap* Using Arrays" instead of "Implementation of Min-Heap Using Arrays"

**Comment by BassamMasry** [comment]
A pull request was made fixing the typo

**Comment by A-Alaa** [comment]
The next slides actually are dedicated for a min-heap, so we can just remove the irrelevant figure in the same slide (done). You can revoke the pull request, and re-update your fork.

**Comment by BassamMasry** [comment]
A very stupid questions that really should not come out of me.....
how can I re-update a fork? 😅

**Comment by A-Alaa** [comment]
add a new remote pointing to the original repository, you can call it `upstream`.
then `git pull upstream master`.
